
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uorxqetknrhbocmlwhqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvcnhxZXRrbnJoYm9jbWx3aHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTM4NTEsImV4cCI6MjA2MTUyOTg1MX0.icK5_hGtLIEH6GbP-7yMWphyso7UHqAqlLlOazpf0Q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
